### ISSUE TITLE
[Bug] chapter markers not in the position they are set to

### ISSUE THREAD

**Issue by joshinils** [ajayyy/SponsorBlock#1509]
the gap in the seek-bar is not in the right place
https://www.youtube.com/watch?v=BZBeYpUtfYc

the name of the chapter changes at a different spot (correct) to where the gap is displayed
![image](https://user-images.githubusercontent.com/34302971/193610442-7163f66b-eb2e-47f2-a7a2-874f8218446b.png)![image](https://user-images.githubusercontent.com/34302971/193610485-1e56cf6e-47a6-4405-8784-613667512496.png)![image](https://user-images.githubusercontent.com/34302971/193610503-daaffab9-48d0-4bd5-820d-ff44adf04e65.png)

the relevant chapter timestamps are:
7:45.077 - 8:24.790 Martin
8:25.090 - 9:15.847 Alina

but the visible gap in the bar is at about 8:21 / 8:22

**Comment by ajayyy** [comment]
Think this is fixed

**Comment by joshinils** [comment]
v. 5.0.7
not for me

**Comment by ajayyy** [comment]
Try waiting for 5.1.1

**Comment by joshinils** [comment]
no :confused: i manually made firefox check for updates, now i have v. 5.1.1.
still the same for me.
