### ISSUE TITLE
Restarts at 0:00 when skipping a Sponsor

### ISSUE THREAD

**Issue by OmegaRejectz** [ajayyy/SponsorBlock#1818]
While watching videos (while not in a playlist. *might happen in playlists, but can't confirm) when it skips a sponsor it just goes back to 0:00.
I've had this issue occur on 3 seperate videos.

Not sure what other info I could/should include.

**Comment by gelvinp** [comment]
This has happened to me basically the entire time I've used sponsorblock. In my experience, it usually happens when a skipped segment extends to the very end of the video.

**Comment by OmegaRejectz** [comment]
> This has happened to me basically the entire time I've used sponsorblock. In my experience, it usually happens when a skipped segment extends to the very end of the video.

I've had the latter issue probably 100% of the time. However, a couple weeks ago I left a report and it got fixed a couple days later. It had completely fixed the restarting the video after a sponsor segment that goes to the end of the video.

However, a few days after that fix released I now have this issue where it restarts the video even when that segment isn't near the end.

**Comment by robwakefield** [comment]
This issue is still present when watching the video in pop-out mode in firefox

**Comment by ajayyy** [comment]
I believe this will be fixed by https://github.com/ajayyy/SponsorBlock/commit/c8c141f5c9f0082863d9c3304c0cad17fe394b84
