### ISSUE TITLE
Adblocker warning with setting "Ignore Unlisted/Private Videos" and youtube-nocookie embeds

### ISSUE THREAD

**Issue by chk1** [ajayyy/SponsorBlock#464]
Sponsorblock 2.0.5.1
Firefox 80.0 - some addons including uBlock Origin
Firefox 81.0b8 (Developer Edition) - all default settings, no other addons

## Steps to reproduce

* Turn on "Ignore Unlisted/Private Videos"
* Visit website with youtube-nocookie ("privacy-enhanced") embedded video

## Problem

The following message always appears as a Javascript `alert` a short time after page load:

> It seems that something is blocking SponsorBlock's ability to get video data. This is probably your ad blocker. Please check https://github.com/ajayyy/SponsorBlock/wiki/Fix-Ad-Blocker-Blocking-SponsorBlock's-Requests

None of the URLs in the Wiki are being blocked from what I can tell, in the uBO logs, Firefox devtools and browser console. I tried adding the recommended settings to my uBO filter list but there was no difference. Playing with Firefox' tracking, privacy and autoplay controls made no difference either.

I do not have any other network or DNS-type blockers installed. 

## Examples

    <iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/bhGIf8KP2-w" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

This particular video does not have SponsorBlock data (very short video), the alert is shown
https://jsfiddle.net/ryo5wsak/

This video has endcards in the SB database, the alert is shown, and the SB data is still being loaded successfully (setting Endcards - Show in seek bar)
https://jsfiddle.net/nsqk5p3f/

**Comment by ajayyy** [comment]
Ah, I think this is caused by requesting a youtube.com API from a non-youtube domain. I should check if the watch.

[getVideoInfo()](https://github.com/ajayyy/SponsorBlock/blob/39bf141e79fa3e03487834ec1533d4d61f4850cc/src/content.ts#L731) should use the current domain, not just YouTube.com.

youtube-nocooke.com/get_video_info does work.

Will have to test if this breaks on invidious as well

**Comment by ajayyy** [comment]
Should be fixed

**Comment by sivizius** [comment]
Does not seem to be fixed (added this addon to firefox today and enabled this option), version 2.0.11.2 (last update January 23, 2021). I have uMatrix, uBlock Origin and Privacy Budger installed, but I disabled them and the error is still there. However,  can live with disabling the option.

**Comment by ajayyy** [comment]
I've been getting many reports about this recently for non cookie stuff too, so maybe YouTube changed something

**Comment by ajayyy** [comment]
@sivizius Can you check the console on the YouTube page for the following error?

```[SB] Failed at getting video info from YouTube.```

If you find that, can you try it again with the latest beta (https://github.com/ajayyy/SponsorBlock/releases/tag/2.0.12.1), I made it log the data it got from YouTube if it is unable to parse it. If you see that, send the log here.

**Comment by sivizius** [comment]
Nope, only unrelated errors (like Content Security Policy and Cross Origin Request Block)

**Comment by ajayyy** [comment]
This warning doesn't exist anymore
